#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "owncloud"
name = "ownCloud classic"
description.en = "Online storage, file sharing platform - Classic Edition"
description.fr = "Stockage en ligne, plateforme de partage de fichiers - Édition Classique"

version = "11.0.0~ynh1"

maintainers = ["didierchavaroche"]

[upstream]
license = "AGPL-3.0"
website = "https://owncloud.com"
demo = "https://demo.owncloud.com/"
admindoc = "https://doc.owncloud.com/server/latest/admin_manual/"
userdoc = "https://doc.owncloud.com/server/latest/user_manual/en/"
code = "https://github.com/owncloud/core"
cpe = "cpe:2.3:a:owncloud:owncloud"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = true
sso = true

disk = "500M"
ram.build = "500M"
ram.runtime = "128M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/owncloud"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["cs", "de", "en", "es", "fr", "gl", "it"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources.main]
    url = "https://github.com/owncloud/core/releases/download/v11.0.0/owncloud-complete-20260730.tar.bz2"
    sha256 = "747fcbb48a2df5d1ef61b87768a4e3484184469b876a76a8070e5c026f6396b3"
    in_subdir = false

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    subdirs = ["data", "config"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]

    [resources.apt]
    packages = [
        "mariadb-server",
        "php8.3-mysql",
        "php8.3-gd",
        "php8.3-curl",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-zip",
        "php8.3-bz2",
        "php8.3-intl",
        "php8.3-imagick",
        "php8.3-ldap"
        "imagemagick",
        "redis-server",
        "php8.3-redis",
    ]

    [resources.database]
    type = "mysql"
