php_admin_value[error_log] = /var/log/$pool.log
php_admin_flag[log_errors] = on
php_admin_flag[catch_workers_output] = on

php_value[session.save_handler] = files
php_value[session.save_path] = /var/lib/php/sessions
php_value[soap.wsdl_cache_dir] = /tmp

php_value[upload_max_filesize] = 16G
php_value[post_max_size] = 16G
php_value[max_execution_time] = 3600
php_value[max_input_time] = 3600
php_value[memory_limit] = 512M
php_value[opcache.enable] = 1
php_value[opcache.enable_cli] = 1
php_value[opcache.memory_consumption] = 128
php_value[opcache.interned_strings_buffer] = 8
php_value[opcache.max_accelerated_files] = 4000
php_value[opcache.revalidate_freq] = 2
php_value[opcache.fast_shutdown] = 1

; Set open_basedir to restrict file access
;php_admin_value[open_basedir] = /var/www/__APP__/:/tmp/:/var/tmp/:/usr/share/php/:/etc/php/8.3/:/dev/urandom

