[Definition]
failregex = ^.*"POST.*login.*HTTP/.*" 401 .*$
            ^.*"POST.*login.*HTTP/.*" 403 .*$
            ^.*"GET.*login.*HTTP/.*" 401 .*$
            ^.*"GET.*login.*HTTP/.*" 403 .*$
ignoreregex =
